const ADD_PARTIAL_BLOGS = 'ADD_PARTIAL_BLOGS';
const UPDATE_PARTIAL_BLOGS = 'UPDATE_PARTIAL_BLOGS';
const LOAD_PARTIAL_BLOGS = 'LOAD_PARTIAL_BLOGS';
const ADD_BLOG_URLS = 'ADD_BLOG_URLS';
const ADD_BLOG = 'ADD_BLOG';
const INIT_AUTHORS = 'INIT_AUTHORS';
const CLEAR_AUTHOR_FILTER = 'CLEAR_AUTHOR_FILTER';
const UPDATE_AUTHOR_FILTER = 'UPDATE_AUTHOR_FILTER';

export {
  ADD_PARTIAL_BLOGS,
  UPDATE_PARTIAL_BLOGS,
  LOAD_PARTIAL_BLOGS,
  ADD_BLOG_URLS,
  ADD_BLOG,
  INIT_AUTHORS,
  CLEAR_AUTHOR_FILTER,
  UPDATE_AUTHOR_FILTER,
};
